name: generate metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: PlainJane20
          template: classic
          filename: metrics.svg
          committer_branch: output
          base: "header"
          config_display: compact
          config_timezone: America/Los_Angeles
